/**
 * save.service.js
 * Builds all Timetable documents and saves them to Mongoose collection using insertMany().
 */

import Timetable from '../../models/Timetable.js';

export const saveGeneratedTimetables = async (
  schoolId,
  academicYearId,
  classSections,
  classSchedule,
  config,
  workingDays,
  periodsPerDay
) => {
  const timetablesToSave = [];
  const periodTimings = config.periodTimings || [];

  for (const cs of classSections) {
    const classId = cs.schoolClass._id;
    const sectionId = cs.section._id;
    const keyPrefix = `${classId}-${sectionId}`;

    const periodsList = [];

    for (const day of workingDays) {
      for (let p = 1; p <= periodsPerDay; p++) {
        const slotKey = `${keyPrefix}-${day}-${p}`;
        const timing = periodTimings.find(t => t.periodNo === p);
        
        const scheduleItem = classSchedule.get(slotKey);

        if (scheduleItem) {
          periodsList.push({
            day,
            periodNo: p,
            startTime: timing?.startTime || '',
            endTime: timing?.endTime || '',
            subject: scheduleItem.subjectId || null,
            teacher: scheduleItem.teacherId || null,
            room: scheduleItem.room || '',
            isLunch: scheduleItem.isLunch || false,
            isBreak: scheduleItem.isBreak || false,
            isAssembly: scheduleItem.isAssembly || false,
            isFixed: scheduleItem.isFixed || false,
            label: scheduleItem.label || '',
            isLocked: false
          });
        } else {
          // Empty teaching slot
          periodsList.push({
            day,
            periodNo: p,
            startTime: timing?.startTime || '',
            endTime: timing?.endTime || '',
            subject: null,
            teacher: null,
            room: '',
            isLunch: false,
            isBreak: false,
            isAssembly: false,
            isFixed: false,
            label: '',
            isLocked: false
          });
        }
      }
    }

    // Delete existing draft if any (published ones were locked and skipped during generation)
    await Timetable.deleteMany({
      schoolId,
      schoolClass: classId,
      section: sectionId,
      academicYear: academicYearId,
      status: 'draft'
    });

    timetablesToSave.push({
      schoolId,
      schoolClass: classId,
      section: sectionId,
      academicYear: academicYearId,
      periods: periodsList,
      totalPeriodsPerDay: periodsPerDay,
      lunchBreakAfter: config.lunchBreaks?.[0]?.afterPeriod || 4,
      isAutoGenerated: true,
      status: 'draft',
      configSnapshot: config.toObject ? config.toObject() : config,
      version: 1
    });
  }

  // Bulk Insert
  let savedDocs = [];
  if (timetablesToSave.length > 0) {
    savedDocs = await Timetable.insertMany(timetablesToSave);
  }

  return {
    savedCount: savedDocs.length,
    savedPeriods: savedDocs.reduce((sum, doc) => sum + doc.periods.length, 0)
  };
};
