import mongoose from 'mongoose';

const periodSchema = new mongoose.Schema({
  day: { type: Number, required: true, min: 0, max: 6 },
  periodNo: { type: Number, required: true },
  subject: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject' },
  teacher: { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher' },
  room: String,
  isLunch: { type: Boolean, default: false },
  isBreak: { type: Boolean, default: false },
}, { _id: false });

const timetableSchema = new mongoose.Schema({
  schoolId: { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true },
  schoolClass: { type: mongoose.Schema.Types.ObjectId, ref: 'SchoolClass', required: true },
  section: { type: mongoose.Schema.Types.ObjectId, ref: 'Section', required: true },
  academicYear: { type: mongoose.Schema.Types.ObjectId, ref: 'AcademicYear', required: true },
  periods: [periodSchema],
  totalPeriodsPerDay: { type: Number, default: 8 },
  lunchBreakAfter: { type: Number, default: 4 },
  status: { type: String, enum: ['draft', 'published'], default: 'draft' },
  isAutoGenerated: { type: Boolean, default: false },
  constraints: {
    teacherMaxPeriodsPerDay: { type: Number, default: 6 },
    subjectWeeklyLimits: { type: Map, of: Number },
  },
}, { timestamps: true });

timetableSchema.index({ schoolId: 1, schoolClass: 1, section: 1, academicYear: 1 }, { unique: true });

export default mongoose.model('Timetable', timetableSchema);
