import mongoose from 'mongoose';

const periodSchema = new mongoose.Schema({
  day: { type: Number, required: true, min: 0, max: 6 },
  periodNo: { type: Number, required: true, min: 1 },
  subject: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject' },
  teacher: { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher' },
  room: { type: String, trim: true },

  // Period type flags
  isLunch: { type: Boolean, default: false },
  isBreak: { type: Boolean, default: false },
  isAssembly: { type: Boolean, default: false },
  isFixed: { type: Boolean, default: false },
  isLocked: { type: Boolean, default: false },

  // Time info
  startTime: { type: String },
  endTime: { type: String },
  label: { type: String, trim: true },

  // Consecutive period tracking (double periods)
  isConsecutiveStart: { type: Boolean, default: false },
  consecutiveGroupId: { type: String },
}, { _id: false });

const conflictLogSchema = new mongoose.Schema({
  type: { type: String, required: true },
  severity: { type: String, enum: ['error', 'warning', 'info'], default: 'error' },
  message: { type: String, required: true },
  context: { type: mongoose.Schema.Types.Mixed },
}, { _id: false });

const timetableSchema = new mongoose.Schema({
  schoolId: { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true },
  schoolClass: { type: mongoose.Schema.Types.ObjectId, ref: 'SchoolClass', required: true },
  section: { type: mongoose.Schema.Types.ObjectId, ref: 'Section', required: true },
  academicYear: { type: mongoose.Schema.Types.ObjectId, ref: 'AcademicYear', required: true },

  periods: [periodSchema],
  totalPeriodsPerDay: { type: Number, default: 8 },
  lunchBreakAfter: { type: Number, default: 4 },

  status: { type: String, enum: ['draft', 'published'], default: 'draft' },
  isAutoGenerated: { type: Boolean, default: false },

  // Versioning and generation metadata
  version: { type: Number, default: 1 },
  generatedAt: { type: Date },
  generationLog: [conflictLogSchema],

  // Locked periods survive regeneration
  lockedPeriods: [{
    day: { type: Number, min: 0, max: 6 },
    periodNo: { type: Number, min: 1 },
    _id: false,
  }],

  // Snapshot of config used during generation
  configSnapshot: { type: mongoose.Schema.Types.Mixed },

  // Legacy compat
  constraints: {
    teacherMaxPeriodsPerDay: { type: Number, default: 6 },
    subjectWeeklyLimits: { type: Map, of: Number },
  },
}, { timestamps: true });

timetableSchema.index({ schoolId: 1, schoolClass: 1, section: 1, academicYear: 1 }, { unique: true });
timetableSchema.index({ schoolId: 1, academicYear: 1 });
timetableSchema.index({ schoolId: 1, status: 1 });

export default mongoose.model('Timetable', timetableSchema);
