import Timetable from '../models/Timetable.js';
import Subject from '../models/Subject.js';
import Teacher from '../models/Teacher.js';
import ApiError from '../utils/ApiError.js';
import { TimetableGenerator } from '../utils/timetableEngine.js';
import { paginate } from '../utils/pagination.js';

export const generateTimetable = async (schoolId, data) => {
  const existing = await Timetable.findOne({ schoolId, schoolClass: data.schoolClass, section: data.section, academicYear: data.academicYear });
  if (existing) throw new ApiError(409, 'Timetable already exists for this class/section. Delete it first to regenerate.');

  const subjects = await Subject.find({ schoolId, classes: data.schoolClass });
  const teachers = await Teacher.find({ schoolId, assignedClasses: data.schoolClass });

  const subjectWeeklyLimits = {};
  subjects.forEach((s) => { subjectWeeklyLimits[s._id.toString()] = s.weeklyPeriods || 5; });

  const generator = new TimetableGenerator({
    schoolClass: data.schoolClass,
    section: data.section,
    subjects,
    teachers,
    periodsPerDay: data.periodsPerDay || 8,
    lunchAfter: data.lunchBreakAfter || 4,
    workingDays: [1, 2, 3, 4, 5],
    holidays: [],
    subjectWeeklyLimits,
  });

  const periods = generator.generate();

  const conflicts = generator.validate();
  if (conflicts.length > 0) {
    throw new ApiError(409, 'Timetable generation produced conflicts', conflicts);
  }

  const timetable = await Timetable.create({
    schoolId,
    schoolClass: data.schoolClass,
    section: data.section,
    academicYear: data.academicYear,
    periods,
    totalPeriodsPerDay: data.periodsPerDay || 8,
    lunchBreakAfter: data.lunchBreakAfter || 4,
    isAutoGenerated: true,
    constraints: { subjectWeeklyLimits },
    status: 'draft',
  });

  return timetable;
};

export const getTimetables = async (schoolId, options) => {
  return paginate(Timetable, { schoolId }, options);
};

export const getTimetableById = async (id, schoolId) => {
  const timetable = await Timetable.findOne({ _id: id, schoolId })
    .populate('schoolClass', 'name')
    .populate('section', 'name')
    .populate('academicYear', 'name')
    .populate('periods.subject', 'name code')
    .populate('periods.teacher', 'firstName lastName');
  if (!timetable) throw new ApiError(404, 'Timetable not found');
  return timetable;
};

export const getTimetableByClassSection = async (schoolId, classId, sectionId) => {
  const timetable = await Timetable.findOne({ schoolId, schoolClass: classId, section: sectionId, status: 'published' })
    .populate('periods.subject', 'name code')
    .populate('periods.teacher', 'firstName lastName');
  if (!timetable) return null;
  return timetable;
};

export const updateTimetablePeriods = async (id, schoolId, periods) => {
  const timetable = await Timetable.findOne({ _id: id, schoolId });
  if (!timetable) throw new ApiError(404, 'Timetable not found');

  const conflicts = TimetableGenerator.detectConflicts(periods);
  if (conflicts.length > 0) {
    throw new ApiError(409, 'Timetable has conflicts', conflicts);
  }

  timetable.periods = periods;
  await timetable.save();
  return timetable;
};

export const publishTimetable = async (id, schoolId, status) => {
  const timetable = await Timetable.findOneAndUpdate({ _id: id, schoolId }, { status }, { new: true });
  if (!timetable) throw new ApiError(404, 'Timetable not found');
  return timetable;
};

export const deleteTimetable = async (id, schoolId) => {
  const timetable = await Timetable.findOneAndDelete({ _id: id, schoolId });
  if (!timetable) throw new ApiError(404, 'Timetable not found');
  return true;
};

export const findSubstitutes = async (schoolId, absentTeacherId, targetPeriodId) => {
  const timetable = await Timetable.findOne({ 'periods._id': targetPeriodId, schoolId });
  if (!timetable) throw new ApiError(404, 'Timetable period not found');

  const period = timetable.periods.id(targetPeriodId);
  if (!period) throw new ApiError(404, 'Period not found');

  const allTeachers = await Teacher.find({ schoolId, status: 'active' });
  const allSubjects = await Subject.find({ schoolId });

  const { SubstituteEngine } = await import('../utils/substituteEngine.js');
  const candidates = SubstituteEngine.findSubstitutes(absentTeacherId, period.subject, period.day, period.periodNo, allTeachers, allSubjects);

  return candidates;
};
