import { describe, it, expect, beforeEach, afterEach, jest } from '@jest/globals';

jest.unstable_mockModule('puppeteer', () => ({
  default: {
    launch: jest.fn().mockResolvedValue({
      newPage: jest.fn(),
      close: jest.fn(),
    }),
  },
}));

const mongoose = (await import('mongoose')).default;
const { createManualTimetable } = await import('../timetable.service.js');
const { createTimetableSchema } = await import('../../validators/timetable.validator.js');
const Timetable = (await import('../../models/Timetable.js')).default;
const SchoolClass = (await import('../../models/SchoolClass.js')).default;
const Section = (await import('../../models/Section.js')).default;
const TimetableConfig = (await import('../../models/TimetableConfig.js')).default;
const Teacher = (await import('../../models/Teacher.js')).default;
const Subject = (await import('../../models/Subject.js')).default;

describe('Manual Timetable Service Unit Tests', () => {
  const schoolId = new mongoose.Types.ObjectId().toString();
  const classId = new mongoose.Types.ObjectId().toString();
  const sectionId = new mongoose.Types.ObjectId().toString();
  const academicYearId = new mongoose.Types.ObjectId().toString();

  let originals = {};

  beforeEach(() => {
    originals = {
      TimetableFindOne: Timetable.findOne,
      TimetableCreate: Timetable.create,
      TimetableFindById: Timetable.findById,
      SchoolClassFindOne: SchoolClass.findOne,
      SectionFindOne: Section.findOne,
      TimetableConfigFindOne: TimetableConfig.findOne,
      TimetableConfigCreate: TimetableConfig.create,
      TeacherFind: Teacher.find,
      SubjectFind: Subject.find,
    };
  });

  afterEach(() => {
    Timetable.findOne = originals.TimetableFindOne;
    Timetable.create = originals.TimetableCreate;
    Timetable.findById = originals.TimetableFindById;
    SchoolClass.findOne = originals.SchoolClassFindOne;
    Section.findOne = originals.SectionFindOne;
    TimetableConfig.findOne = originals.TimetableConfigFindOne;
    TimetableConfig.create = originals.TimetableConfigCreate;
    Teacher.find = originals.TeacherFind;
    Subject.find = originals.SubjectFind;
    jest.restoreAllMocks();
  });

  describe('createTimetableSchema validator', () => {
    it('should validate valid manual timetable payload', () => {
      const validPayload = {
        schoolClass: classId,
        section: sectionId,
        academicYear: academicYearId,
        status: 'draft',
        totalPeriodsPerDay: 8,
        lunchBreakAfter: 4,
        periods: [],
      };
      const parsed = createTimetableSchema.safeParse(validPayload);
      expect(parsed.success).toBe(true);
    });

    it('should fail when class or section is missing', () => {
      const invalid = {
        academicYear: academicYearId,
      };
      const parsed = createTimetableSchema.safeParse(invalid);
      expect(parsed.success).toBe(false);
    });
  });

  describe('createManualTimetable service', () => {
    it('should throw 404 if class is not found', async () => {
      SchoolClass.findOne = jest.fn().mockResolvedValue(null);
      Section.findOne = jest.fn().mockResolvedValue({ _id: sectionId });

      await expect(
        createManualTimetable(schoolId, {
          schoolClass: classId,
          section: sectionId,
          academicYear: academicYearId,
        })
      ).rejects.toThrow('Class not found');
    });

    it('should throw 404 if section is not found', async () => {
      SchoolClass.findOne = jest.fn().mockResolvedValue({ _id: classId });
      Section.findOne = jest.fn().mockResolvedValue(null);

      await expect(
        createManualTimetable(schoolId, {
          schoolClass: classId,
          section: sectionId,
          academicYear: academicYearId,
        })
      ).rejects.toThrow('Section not found');
    });

    it('should throw 409 if timetable already exists for this class and section', async () => {
      SchoolClass.findOne = jest.fn().mockResolvedValue({ _id: classId });
      Section.findOne = jest.fn().mockResolvedValue({ _id: sectionId });
      Timetable.findOne = jest.fn().mockResolvedValue({ _id: 'existing-id' });

      await expect(
        createManualTimetable(schoolId, {
          schoolClass: classId,
          section: sectionId,
          academicYear: academicYearId,
        })
      ).rejects.toThrow('A timetable already exists for this class and section');
    });

    it('should create manual timetable with isAutoGenerated: false', async () => {
      SchoolClass.findOne = jest.fn().mockResolvedValue({ _id: classId, name: 'Grade 10' });
      Section.findOne = jest.fn().mockResolvedValue({ _id: sectionId, name: 'A' });
      Timetable.findOne = jest.fn().mockResolvedValue(null);
      TimetableConfig.findOne = jest.fn().mockResolvedValue({
        periodsPerDay: 8,
        lunchBreaks: [{ afterPeriod: 4 }],
        toObject: () => ({ periodsPerDay: 8 }),
      });

      const mockCreated = {
        _id: new mongoose.Types.ObjectId().toString(),
        schoolId,
        schoolClass: classId,
        section: sectionId,
        academicYear: academicYearId,
        isAutoGenerated: false,
        status: 'draft',
      };

      Timetable.create = jest.fn().mockResolvedValue(mockCreated);

      const populateChain = {
        populate: jest.fn().mockReturnThis(),
      };
      populateChain.populate
        .mockReturnValueOnce(populateChain)
        .mockReturnValueOnce(populateChain)
        .mockReturnValueOnce(populateChain)
        .mockReturnValueOnce(populateChain)
        .mockResolvedValueOnce({
          ...mockCreated,
          schoolClass: { _id: classId, name: 'Grade 10' },
          section: { _id: sectionId, name: 'A' },
        });

      Timetable.findById = jest.fn().mockReturnValue(populateChain);

      const result = await createManualTimetable(schoolId, {
        schoolClass: classId,
        section: sectionId,
        academicYear: academicYearId,
      });

      expect(Timetable.create).toHaveBeenCalledWith(
        expect.objectContaining({
          schoolId,
          schoolClass: classId,
          section: sectionId,
          academicYear: academicYearId,
          isAutoGenerated: false,
          status: 'draft',
        })
      );
      expect(result).toBeDefined();
      expect(result.schoolClass.name).toBe('Grade 10');
    });
  });
});
